name: Dev Container Build and Push Image

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    pull_requests:
      branches:
        - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}
        if: github.event_name != 'pull_request'

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        strategy:
          matrix:
            image: [base, dart, java, javascript]
        with:
          subFolder: .github/devcontainer//${{ matrix.image }}
          imageName: ghcr.io/${{ github.repository }}/${{ matrix.image }}
          cacheFrom: ghcr.io/${{ github.repository }}/${{ matrix.image }}
          push: ${{ github.event_name != 'pull_request' && 'always' || 'never' }}
